In [2]:
import geopandas as gp
import pandas as pd
import numpy as np

# To build: python3 -m numpy.f2py -c geodinverse.for geodesic.for -m geof
import geof

In [3]:
gdf = gp.read_file("../crop_shapes/i15_Crop_Mapping_2016.shp")

In [4]:
gdf.shape

(390666, 39)

In [6]:
gdf.columns[1:38]

Index(['DWR_revise', 'Symb_class', 'MULTIUSE', 'CLASS1', 'SUBCLASS1',
       'SPECOND1', 'IRR_TYP1PA', 'IRR_TYP1PB', 'PCNT1', 'CLASS2', 'SUBCLASS2',
       'SPECOND2', 'IRR_TYP2PA', 'IRR_TYP2PB', 'PCNT2', 'CLASS3', 'SUBCLASS3',
       'SPECOND3', 'IRR_TYP3PA', 'IRR_TYP3PB', 'PCNT3', 'UCF_ATT', 'CROPTYP1',
       'CROPTYP2', 'CROPTYP3', 'Region', 'Acres', 'County', 'Comments',
       'Source', 'Crop2016', 'Modified_B', 'Date_Data_', 'Last_Modif',
       'GlobalID', 'Shape_Leng', 'Shape_Area'],
      dtype='object')

In [7]:
# Convert from NAD83 to WGS84
gdf = gdf.to_crs("EPSG:4326")

In [8]:
gdf = gdf[gdf["County"] == "Fresno"]

In [9]:
gdf.shape

(36972, 39)

In [10]:
zdf = gdf[gdf.columns[1:38]]

In [11]:
zdf.to_csv("../crop_shapes.csv")

In [12]:
gdf.Crop2016.value_counts()

Grapes                                       7357
Idle                                         5312
Almonds                                      4279
Citrus                                       3207
Peaches/Nectarines                           2213
Young Perennials                             1666
Tomatoes                                     1376
Pistachios                                   1150
Miscellaneous Truck Crops                    1140
Plums, Prunes and Apricots                   1125
Cotton                                        945
Alfalfa and Alfalfa Mixtures                  930
Corn, Sorghum and Sudan                       793
Mixed Pasture                                 753
Wheat                                         661
Miscellaneous Grain and Hay                   510
Melons, Squash and Cucumbers                  488
Miscellaneous Deciduous                       466
Onions and Garlic                             466
Walnuts                                       454
Cherries                                      339
Pomegranates                                  188
Lettuce/Leafy Greens                          185
Bush Berries                                  148
Miscellaneous Grasses                         124
Flowers, Nursery and Christmas Tree Farms     113
Olives                                         97
Cole Crops                                     80
Apples                                         78
Kiwis                                          58
Beans (Dry)                                    54
Peppers                                        53
Pears                                          41
Carrots                                        37
Strawberries                                   23
Rice                                           22
Dates                                          12
Safflower                                       8
Greenhouse                                      7
Sunflowers                                      6
Miscellaneous Subtropical Fruits                5
Potatoes and Sweet Potatoes                     1
Avocados                                        1
Miscellaneous Field Crops                       1
Name: Crop2016, dtype: int64

In [13]:
centroids = gdf.centroid

In [14]:
centroids.index

Int64Index([ 37477,  37478,  37479,  37480,  37481,  37482,  37497,  37498,
             37500,  39364,
            ...
            183336, 183337, 183346, 183347, 183348, 183349, 183380, 183608,
            183617, 183622],
           dtype='int64', length=36972)

In [16]:
zdf.index

Int64Index([ 37477,  37478,  37479,  37480,  37481,  37482,  37497,  37498,
             37500,  39364,
            ...
            183336, 183337, 183346, 183347, 183348, 183349, 183380, 183608,
            183617, 183622],
           dtype='int64', length=36972)

In [1]:
centroids

NameError: name 'centroids' is not defined

In [11]:
df = pd.read_csv("../ca_fresno.csv")

/home/draget/.local/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3063: DtypeWarning: Columns (42,46,50,51,57,93) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [12]:
lats = df["lat"].values
longs = df["lng"].values
pnumb = df["parcelnumb"].values

In [13]:
~((df["lot_area"] < 0.5) & (df["usecode"] == 'S01'))

0          True
1          True
2          True
3          True
4          True
          ...
419965     True
419966    False
419967     True
419968     True
419969    False
Length: 419970, dtype: bool

In [14]:
df = df[~((df["lot_area"] < 0.5) & (df["usecode"] == 'S01'))]
df = df[~(df["usecode"].str.match('A[0-9]+').fillna(False))]

In [15]:
df.shape

(145363, 104)

In [16]:
%load_ext line_profiler

In [21]:
%lprun -f findcrop findcrop([37.0874484033331, -119.42914487491699, '128z'])

In [20]:
findcrop([36.58477, -119.439163, '128z'])

['128z', 149683, array([9.7909217, 'Grapes'], dtype=object)]

In [ ]:
ll = df[["lat", "lng", "parcelnumb"]].values

In [22]:
from multiprocessing import Pool
pool = Pool(processes = 6)

parcel_crop = pool.map(findcrop, ll)

In [127]:
pcdf = pd.DataFrame(parcel_crop)

pcdf2_l = []
for r in pcdf[2].tolist():
    if r is None:
        pcdf2_l.append([0.0,'' ])
    else:
        pcdf2_l.append([r[0],r[1]])

In [128]:
pcdf.columns = ["parcelnumb", "gdfindex", "cropdata"]
pcdf2 = pd.DataFrame(pcdf2_l, columns = ["Acres", "Crop2016"])
pcdf = pd.merge(pcdf, pcdf2, left_index = True, right_index = True)
pcdf.drop("cropdata", axis = 1, inplace = True)

In [129]:
pd.set_option('display.max_rows', 500)

pcdf.head(500)

     parcelnumb  gdfindex      Acres                      Crop2016
0      12830112       NaN   0.000000
1      12817026       NaN   0.000000
2      12830219       NaN   0.000000
3      12830132       NaN   0.000000
4      11616008       NaN   0.000000
5      11602004       NaN   0.000000
6      12830140       NaN   0.000000
7      06518168       NaN   0.000000
8      11822068       NaN   0.000000
9      11614014       NaN   0.000000
10     11615018       NaN   0.000000
11     12010005       NaN   0.000000
12     11614005       NaN   0.000000
13     11614011       NaN   0.000000
14     11614009       NaN   0.000000
15     11615017       NaN   0.000000
16     11616046       NaN   0.000000
17     12828013       NaN   0.000000
18   01328008ST       NaN   0.000000
19     30023X0O       NaN   0.000000
20     12017409       NaN   0.000000
21     11603023       NaN   0.000000
22     11616054       NaN   0.000000
23     11616009       NaN   0.000000
24     11616051       NaN   0.000000
25     11603026       NaN   0.000000
26     12828013       NaN   0.000000
27     55502060       NaN   0.000000
28     55502060       NaN   0.000000
29     45625113       NaN   0.000000
30     37002003  149683.0   9.790922                        Grapes
31    11617007S       NaN   0.000000
32     36309061  176992.0   4.597083       Miscellaneous Deciduous
33     40616121       NaN   0.000000
34    05326007T  153377.0   4.214982                       Almonds
35     11603036       NaN   0.000000
36     11602008       NaN   0.000000
37     12830139       NaN   0.000000
38     12817001       NaN   0.000000
39     41628130       NaN   0.000000
40     12817022       NaN   0.000000
41     31320215       NaN   0.000000
42    11617007S       NaN   0.000000
43     11603045       NaN   0.000000
44     55502060       NaN   0.000000
45     13040519       NaN   0.000000
46     12835081       NaN   0.000000
47     30932018  150354.0   1.859248     Miscellaneous Truck Crops
48     12034212       NaN   0.000000
49     31342037  178083.0  15.558470                          Idle
50     31342037  178083.0  15.558470                          Idle
51     31342037  178083.0  15.558470                          Idle
52    58105022S       NaN   0.000000
53     46303030       NaN   0.000000
54     11315210       NaN   0.000000
55     11603037       NaN   0.000000
56     11612009       NaN   0.000000
57     49311408       NaN   0.000000
58     12028204       NaN   0.000000
59     49311408       NaN   0.000000
60     49311408       NaN   0.000000
61     49311408       NaN   0.000000
62     49311408       NaN   0.000000
63     12819001       NaN   0.000000
64     40626058       NaN   0.000000
65     12830129       NaN   0.000000
66     11609008       NaN   0.000000
67     49311408       NaN   0.000000
68    02307119U  176492.0  15.803928                          Idle
69     11611020       NaN   0.000000
70     13085503       NaN   0.000000
71     13068204       NaN   0.000000
72     11603025       NaN   0.000000
73     11606011       NaN   0.000000
74     13040X0C       NaN   0.000000
75     11604009       NaN   0.000000
76     11604008       NaN   0.000000
77     11612011       NaN   0.000000
78     11611019       NaN   0.000000
79    47422605S       NaN   0.000000
80     11614006       NaN   0.000000
81     13051002       NaN   0.000000
82     13023010       NaN   0.000000
83     11859022       NaN   0.000000
84     13051008       NaN   0.000000
85     12824306       NaN   0.000000
86     11824128       NaN   0.000000
87     13040512       NaN   0.000000
88     11614008       NaN   0.000000
89     11614007       NaN   0.000000
90     11611009       NaN   0.000000
91     31252121  178778.0   2.572614                          Idle
92     44207124       NaN   0.000000
93     14023320       NaN   0.000000
94     33522039  173084.0   4.002657                          Idle
95     00124003  155100.0  96.345580                        Cotton
96     14023317       NaN   0.000000
97     14032005       NaN   0.000000
98     13837148       NaN   0.000000
99     13835340       NaN   0.000000
100    13822023       NaN   0.000000
101    13837147       NaN   0.000000
102    13854002       NaN   0.000000
103    15003136       NaN   0.000000
104    30058012       NaN   0.000000
105    14032004       NaN   0.000000
106    30057005       NaN   0.000000
107    15003135       NaN   0.000000
108    15003119       NaN   0.000000
109    15030047       NaN   0.000000
110    13838016       NaN   0.000000
111    13838015       NaN   0.000000
112    13834312       NaN   0.000000
113    13842008       NaN   0.000000
114    12863001       NaN   0.000000
115    12853009       NaN   0.000000
116    14023313       NaN   0.000000
117    14023312       NaN   0.000000
118    14023318       NaN   0.000000
119    14023317       NaN   0.000000
120    14023319       NaN   0.000000
121    14022039       NaN   0.000000
122    14023320       NaN   0.000000
123    13830013       NaN   0.000000
124    14035008       NaN   0.000000
125   58105045S       NaN   0.000000
126    00305218  154393.0   8.691865                      Tomatoes
127    00303023  154376.0  15.702042  Alfalfa and Alfalfa Mixtures
128    58111002       NaN   0.000000
129    58111007       NaN   0.000000
130    58110010       NaN   0.000000
131    58112021   42382.0   1.256682                          Idle
132    58112043  172611.0   3.585135                        Citrus
133    43601004       NaN   0.000000
134    13045026       NaN   0.000000
135    12871010       NaN   0.000000
136    11854037       NaN   0.000000
137    11855009       NaN   0.000000
138    11820211       NaN   0.000000
139    11842220       NaN   0.000000
140    12844150       NaN   0.000000
141    14008113       NaN   0.000000
142    14029044       NaN   0.000000
143    14003121       NaN   0.000000
144    14028115       NaN   0.000000
145    12847061       NaN   0.000000
146    40404035       NaN   0.000000
147    13806136       NaN   0.000000
148    12871049       NaN   0.000000
149    43601004       NaN   0.000000
150    43601004       NaN   0.000000
151    43601004       NaN   0.000000
152    00808035       NaN   0.000000
153    51043408       NaN   0.000000
154    51043408       NaN   0.000000
155    51043408       NaN   0.000000
156    51043408       NaN   0.000000
157    51043408       NaN   0.000000
158    51043408       NaN   0.000000
159    51043408       NaN   0.000000
160    51043408       NaN   0.000000
161    00127002  155067.0  27.904502                      Tomatoes
162    12844150       NaN   0.000000
163    11803150       NaN   0.000000
164    47206010       NaN   0.000000
165    49309305       NaN   0.000000
166   51101208S       NaN   0.000000
167    12869017       NaN   0.000000
168    12869018       NaN   0.000000
169    12879031       NaN   0.000000
170    13837119       NaN   0.000000
171    12849005       NaN   0.000000
172    13837126       NaN   0.000000
173    13834101       NaN   0.000000
174    13837124       NaN   0.000000
175    55502060       NaN   0.000000
176    12871052       NaN   0.000000
177    13834102       NaN   0.000000
178    11854059       NaN   0.000000
179    12871049       NaN   0.000000
180    11854049       NaN   0.000000
181    13834103       NaN   0.000000
182    13834202       NaN   0.000000
183    13823037       NaN   0.000000
184    13814049       NaN   0.000000
185    13047012       NaN   0.000000
186    12841038       NaN   0.000000
187    13823049       NaN   0.000000
188    13838034       NaN   0.000000
189    13835308       NaN   0.000000
190    13818001       NaN   0.000000
191    14028115       NaN   0.000000
192    00126004  155089.0  41.762617  Alfalfa and Alfalfa Mixtures
193   30043010S       NaN   0.000000
194    14021007       NaN   0.000000
195    13822019       NaN   0.000000
196    30058001       NaN   0.000000
197    13837121       NaN   0.000000
198    13822032       NaN   0.000000
199    13815019       NaN   0.000000
200    30058010       NaN   0.000000
201    30058009       NaN   0.000000
202    14032003       NaN   0.000000
203    13819005       NaN   0.000000
204    12807039       NaN   0.000000
205   30050022S       NaN   0.000000
206    14025110       NaN   0.000000
207    14025109       NaN   0.000000
208    14025202       NaN   0.000000
209    12877028       NaN   0.000000
210    12877031       NaN   0.000000
211    13806136       NaN   0.000000
212    43601004       NaN   0.000000
213    14025111       NaN   0.000000
214   30042021S       NaN   0.000000
215    14024009       NaN   0.000000
216    14035007       NaN   0.000000
217    14008116       NaN   0.000000
218    00709119  154561.0  26.378986                        Cotton
219    14008113       NaN   0.000000
220    11849202       NaN   0.000000
221    13834328       NaN   0.000000
222    13834333       NaN   0.000000
223    51043408       NaN   0.000000
224    12847061       NaN   0.000000
225    11853018       NaN   0.000000
226    11849106       NaN   0.000000
227    13834334       NaN   0.000000
228    11855064       NaN   0.000000
229    11855065       NaN   0.000000
230    51108414       NaN   0.000000
231    55502060       NaN   0.000000
232    12811131       NaN   0.000000
233    13834318       NaN   0.000000
234    11820201       NaN   0.000000
235    11820211       NaN   0.000000
236    11820212       NaN   0.000000
237    11820221       NaN   0.000000
238    13834335       NaN   0.000000
239    13834316       NaN   0.000000
240    14003172       NaN   0.000000
241    14003130       NaN   0.000000
242    14003121       NaN   0.000000
243    00118005  157101.0  62.930335                        Cotton
244    13010038       NaN   0.000000
245   30047005S       NaN   0.000000
246    00127002  155067.0  27.904502                      Tomatoes
247    12843062       NaN   0.000000
248   30055010T       NaN   0.000000
249    12843062       NaN   0.000000
250    12843062       NaN   0.000000
251    12863011       NaN   0.000000
252    12843062       NaN   0.000000
253    12843062       NaN   0.000000
254    12843062       NaN   0.000000
255    12843062       NaN   0.000000
256    12843062       NaN   0.000000
257    12843062       NaN   0.000000
258    12843062       NaN   0.000000
259    12843062       NaN   0.000000
260    12843062       NaN   0.000000
261    12843062       NaN   0.000000
262    12843062       NaN   0.000000
263    12843062       NaN   0.000000
264    12843062       NaN   0.000000
265    12843062       NaN   0.000000
266    12843062       NaN   0.000000
267    12843062       NaN   0.000000
268    12843062       NaN   0.000000
269   30031041S       NaN   0.000000
270    12843062       NaN   0.000000
271    12843062       NaN   0.000000
272    12843062       NaN   0.000000
273    12843062       NaN   0.000000
274    12843062       NaN   0.000000
275    12843062       NaN   0.000000
276    12843062       NaN   0.000000
277    12843062       NaN   0.000000
278    12843062       NaN   0.000000
279    12843062       NaN   0.000000
280    12843062       NaN   0.000000
281    12843062       NaN   0.000000
282    12843062       NaN   0.000000
283    12843062       NaN   0.000000
284    12843062       NaN   0.000000
285    12843062       NaN   0.000000
286    12843062       NaN   0.000000
287    12843062       NaN   0.000000
288    12843062       NaN   0.000000
289    12843062       NaN   0.000000
290    12843062       NaN   0.000000
291    12843062       NaN   0.000000
292    12843062       NaN   0.000000
293    12843062       NaN   0.000000
294    12843062       NaN   0.000000
295    12843062       NaN   0.000000
296    12843062       NaN   0.000000
297    12843062       NaN   0.000000
298    12843062       NaN   0.000000
299    12843062       NaN   0.000000
300    12843062       NaN   0.000000
301    12843062       NaN   0.000000
302    12843062       NaN   0.000000
303    12843062       NaN   0.000000
304    12843062       NaN   0.000000
305    12843062       NaN   0.000000
306    55502060       NaN   0.000000
307    12843062       NaN   0.000000
308    12843062       NaN   0.000000
309    12843062       NaN   0.000000
310    12843062       NaN   0.000000
311    12843062       NaN   0.000000
312    12843062       NaN   0.000000
313    12843062       NaN   0.000000
314    12843062       NaN   0.000000
315    12843062       NaN   0.000000
316    12843062       NaN   0.000000
317    12843062       NaN   0.000000
318    12843062       NaN   0.000000
319    11855016       NaN   0.000000
320    12843062       NaN   0.000000
321    12843062       NaN   0.000000
322    12843062       NaN   0.000000
323    12843062       NaN   0.000000
324    12843062       NaN   0.000000
325    12843062       NaN   0.000000
326    12843062       NaN   0.000000
327    12843062       NaN   0.000000
328    12843062       NaN   0.000000
329    12843062       NaN   0.000000
330    12843062       NaN   0.000000
331    12843062       NaN   0.000000
332    12843062       NaN   0.000000
333    12843062       NaN   0.000000
334    12843062       NaN   0.000000
335    12843062       NaN   0.000000
336    12843062       NaN   0.000000
337    12843062       NaN   0.000000
338   30025021T       NaN   0.000000
339    12843062       NaN   0.000000
340    12843062       NaN   0.000000
341    12843062       NaN   0.000000
342    12843062       NaN   0.000000
343    12843062       NaN   0.000000
344    13834332       NaN   0.000000
345    14021013       NaN   0.000000
346    11847228       NaN   0.000000
347    12841039       NaN   0.000000
348    14029036       NaN   0.000000
349    14027018       NaN   0.000000
350    13821049       NaN   0.000000
351    13845019       NaN   0.000000
352    13808133       NaN   0.000000
353    49721236       NaN   0.000000
354    49721236       NaN   0.000000
355    49721236       NaN   0.000000
356    49721236       NaN   0.000000
357    49721236       NaN   0.000000
358    49721236       NaN   0.000000
359    49721236       NaN   0.000000
360    49721236       NaN   0.000000
361    49721236       NaN   0.000000
362    49721236       NaN   0.000000
363    49721236       NaN   0.000000
364    49721236       NaN   0.000000
365    49721236       NaN   0.000000
366    49721236       NaN   0.000000
367   12879002T       NaN   0.000000
368    12879005       NaN   0.000000
369    11855073       NaN   0.000000
370    12871041       NaN   0.000000
371    12863011       NaN   0.000000
372    12871027       NaN   0.000000
373    00305104  154959.0   6.675379                        Cotton
374    14024044       NaN   0.000000
375   14007317S       NaN   0.000000
376    14024031       NaN   0.000000
377    14027023       NaN   0.000000
378    13850001       NaN   0.000000
379    13850006       NaN   0.000000
380    13850021       NaN   0.000000
381    13831054       NaN   0.000000
382    13832005       NaN   0.000000
383    14028213       NaN   0.000000
384    13832004       NaN   0.000000
385    13832030       NaN   0.000000
386    49721236       NaN   0.000000
387    13832028       NaN   0.000000
388    14027018       NaN   0.000000
389    13832007       NaN   0.000000
390    14026019       NaN   0.000000
391    14031013       NaN   0.000000
392    14031005       NaN   0.000000
393    14031010       NaN   0.000000
394    14030011       NaN   0.000000
395    55502060       NaN   0.000000
396    14022016       NaN   0.000000
397    14022017       NaN   0.000000
398    14023202       NaN   0.000000
399    14023201       NaN   0.000000
400    13834332       NaN   0.000000
401    13807032       NaN   0.000000
402    13834107       NaN   0.000000
403    14023203       NaN   0.000000
404    14023204       NaN   0.000000
405    14023205       NaN   0.000000
406    14023206       NaN   0.000000
407    13831045       NaN   0.000000
408    13835323       NaN   0.000000
409    11849107       NaN   0.000000
410    30055007       NaN   0.000000
411    13835322       NaN   0.000000
412    13835326       NaN   0.000000
413   30051001S       NaN   0.000000
414    14021009       NaN   0.000000
415    13807031       NaN   0.000000
416    00128008       NaN   0.000000
417    14028212       NaN   0.000000
418    14021013       NaN   0.000000
419    14028205       NaN   0.000000
420    14028218       NaN   0.000000
421    13834104       NaN   0.000000
422    14028202       NaN   0.000000
423    13815003       NaN   0.000000
424    13837158       NaN   0.000000
425    13831086       NaN   0.000000
426    13837157       NaN   0.000000
427    13821043       NaN   0.000000
428    13837161       NaN   0.000000
429    00119009  155225.0  21.172011  Alfalfa and Alfalfa Mixtures
430    11853008       NaN   0.000000
431    11853015       NaN   0.000000
432    12877032       NaN   0.000000
433    12844176       NaN   0.000000
434    13010024       NaN   0.000000
435    13024011       NaN   0.000000
436    12879004       NaN   0.000000
437    44912232       NaN   0.000000
438    13024008       NaN   0.000000
439    11838029       NaN   0.000000
440    11842216       NaN   0.000000
441    12841039       NaN   0.000000
442    11842214       NaN   0.000000
443    12853007       NaN   0.000000
444    13044033       NaN   0.000000
445    12843062       NaN   0.000000
446    11856003       NaN   0.000000
447    13845016       NaN   0.000000
448    14024003       NaN   0.000000
449    14033013       NaN   0.000000
450    14024002       NaN   0.000000
451    14022024       NaN   0.000000
452    14023121       NaN   0.000000
453    14023311       NaN   0.000000
454    14022025       NaN   0.000000
455    13845019       NaN   0.000000
456    14029036       NaN   0.000000
457   30031041S       NaN   0.000000
458    14024038       NaN   0.000000
459    13829066       NaN   0.000000
460    13828001       NaN   0.000000
461    13854011       NaN   0.000000
462    14023149       NaN   0.000000
463    14025217       NaN   0.000000
464    12844113       NaN   0.000000
465    14032032       NaN   0.000000
466    15030021       NaN   0.000000
467    14025233       NaN   0.000000
468    34338X02       NaN   0.000000
469    14025411       NaN   0.000000
470    13842001       NaN   0.000000
471    13829045       NaN   0.000000
472    13825031       NaN   0.000000
473    14027004       NaN   0.000000
474    14022046       NaN   0.000000
475    14023207       NaN   0.000000
476    14023208       NaN   0.000000
477    14023209       NaN   0.000000
478    14007305       NaN   0.000000
479    14023157       NaN   0.000000
480    14023156       NaN   0.000000
481    14023150       NaN   0.000000
482    13819007       NaN   0.000000
483    13819006       NaN   0.000000
484    14022052       NaN   0.000000
485    13831073       NaN   0.000000
486    14007306       NaN   0.000000
487    14022047       NaN   0.000000
488    14029040       NaN   0.000000
489    14025215       NaN   0.000000
490    14025234       NaN   0.000000
491    14025415       NaN   0.000000
492    14025410       NaN   0.000000
493    14025413       NaN   0.000000
494    14025211       NaN   0.000000
495    14025232       NaN   0.000000
496    11842262       NaN   0.000000
497   38511049T  153708.0  36.381691                        Grapes
498    38511054       NaN   0.000000
499   38511045S  153761.0  46.548856                       Almonds

In [130]:
pcdf.to_pickle("pcdf_1.pkl")

In [18]:
def findcrop(ll):

    ldist = 999999.0
    gdf_index = 0
    
    for j in centroids.index:
        dist = geof.geo_dist(ll[0], ll[1], centroids[j].y, centroids[j].x)

        if(dist < ldist):
            ldist = dist
            gdf_index = j
    
    crop = gdf.loc[gdf_index][["Acres", "Crop2016"]].values
    
    if(crop[0]*0.00405 > ldist**2):
        quality = "Ok"
        return [ll[2], gdf_index, crop]        
    else:
        return [ll[2], None, None]
    
    #print(quality, round(ldist,2), gdf_index, crop, round(ll[0],8), round(ll[1],8), centroids[gdf_index])

In [20]:
from math import radians, sin, cos, sqrt, asin
 
 
def haversine(lat1, lon1, lat2, lon2):
    R = 6370.433  # Earth radius in kilometers
 
    dLat = radians(lat2 - lat1)
    dLon = radians(lon2 - lon1)
    lat1 = radians(lat1)
    lat2 = radians(lat2)
 
    a = sin(dLat / 2)**2 + cos(lat1) * cos(lat2) * sin(dLon / 2)**2
    c = 2 * asin(sqrt(a))
 
    return R * c